In [29]:
import pandas as pd

Overview

In [30]:
df = pd.read_csv(
    "../data/consumption.csv",
    sep=";",
    decimal=",",
    parse_dates=["STARTTID", "SLUTTID"]
)

In [31]:
print("Antall rader og kolonner:", df.shape)
print("\nKolonnenavn og datatyper:")
print(df.dtypes)

print("\nFørste rader:")
print(df.head())

print("\nManglende verdier per kolonne:")
print(df.isnull().sum())

print("\nAntall unike kommuner:", df["KOMMUNE"].nunique())
print("Forbruksgrupper:", df["FORBRUKSGRUPPE"].unique())

print("\nTidsperiode:")
print("Fra:", df["STARTTID"].min())
print("Til:", df["STARTTID"].max())

print("\nDeskriptiv statistikk for volum (kWh):")
print(df["VOLUM_KWH"].describe())

print("\nAntall målepunkter, deskriptiv statistikk:")
print(df["ANTALL_MÅLEPUNKT"].describe())

Antall rader og kolonner: (39951726, 7)

Kolonnenavn og datatyper:
STARTTID             object
SLUTTID              object
KOMMUNE              object
KOMMUNENUMMER         int64
FORBRUKSGRUPPE       object
VOLUM_KWH           float64
ANTALL_MÅLEPUNKT      int64
dtype: object

Første rader:
                    STARTTID                    SLUTTID    KOMMUNE  \
0  2022-02-01 00:00:00+01:00  2022-02-01 01:00:00+01:00   Aarborte
1  2022-02-01 00:00:00+01:00  2022-02-01 01:00:00+01:00   Aarborte
2  2022-02-01 00:00:00+01:00  2022-02-01 01:00:00+01:00   Aarborte
3  2022-02-01 00:00:00+01:00  2022-02-01 01:00:00+01:00  Alstahaug
4  2022-02-01 00:00:00+01:00  2022-02-01 01:00:00+01:00  Alstahaug

   KOMMUNENUMMER FORBRUKSGRUPPE  VOLUM_KWH  ANTALL_MÅLEPUNKT
0           1826     Forretning    481.204                47
1           1826       Industri   1017.999                20
2           1826         Privat   1417.728               559
3           1820     Forretning   6357.571               604
4           1820       Industri   2651.636               135

Manglende verdier per kolonne:
STARTTID            0
SLUTTID             0
KOMMUNE             0
KOMMUNENUMMER       0
FORBRUKSGRUPPE      0
VOLUM_KWH           0
ANTALL_MÅLEPUNKT    0
dtype: int64

Antall unike kommuner: 356
Forbruksgrupper: ['Forretning' 'Industri' 'Privat']

Tidsperiode:
Fra: 2022-02-01 00:00:00+01:00
Til: 2026-04-30 23:00:00+02:00

Deskriptiv statistikk for volum (kWh):
count    3.995173e+07
mean     1.391078e+04
std      4.658252e+04
min     -2.137582e+03
25%      1.326167e+03
50%      3.283141e+03
75%      8.817522e+03
max      1.256062e+07
Name: VOLUM_KWH, dtype: float64

Antall målepunkter, deskriptiv statistikk:
count    3.995173e+07
mean     3.132711e+03
std      1.341891e+04
min      5.000000e+00
25%      1.880000e+02
50%      5.130000e+02
75%      2.192000e+03
max      3.573210e+05
Name: ANTALL_MÅLEPUNKT, dtype: float64

Endre tiden og filtrere

In [32]:
df["STARTTID"] = pd.to_datetime(
    df["STARTTID"],
    utc=True
)

df["SLUTTID"] = pd.to_datetime(
    df["SLUTTID"],
    utc=True
)

df["STARTTID"] = df["STARTTID"].dt.tz_convert("Europe/Oslo")
df["SLUTTID"] = df["SLUTTID"].dt.tz_convert("Europe/Oslo")

df["YEAR"] = df["STARTTID"].dt.year
df["MONTH"] = df["STARTTID"].dt.month
df["DAY"] = df["STARTTID"].dt.day
df["HOUR"] = df["STARTTID"].dt.hour
df["DAY_OF_WEEK"] = df["STARTTID"].dt.dayofweek

In [33]:
df[["STARTTID", "SLUTTID"]].head()

                   STARTTID                   SLUTTID
0 2022-02-01 00:00:00+01:00 2022-02-01 01:00:00+01:00
1 2022-02-01 00:00:00+01:00 2022-02-01 01:00:00+01:00
2 2022-02-01 00:00:00+01:00 2022-02-01 01:00:00+01:00
3 2022-02-01 00:00:00+01:00 2022-02-01 01:00:00+01:00
4 2022-02-01 00:00:00+01:00 2022-02-01 01:00:00+01:00

In [34]:
df[["STARTTID", "SLUTTID"]].dtypes

STARTTID    datetime64[ns, Europe/Oslo]
SLUTTID     datetime64[ns, Europe/Oslo]
dtype: object

In [35]:
df[
    ["STARTTID", "YEAR", "MONTH", "DAY", "HOUR", "DAY_OF_WEEK"]
].head()

                   STARTTID  YEAR  MONTH  DAY  HOUR  DAY_OF_WEEK
0 2022-02-01 00:00:00+01:00  2022      2    1     0            1
1 2022-02-01 00:00:00+01:00  2022      2    1     0            1
2 2022-02-01 00:00:00+01:00  2022      2    1     0            1
3 2022-02-01 00:00:00+01:00  2022      2    1     0            1
4 2022-02-01 00:00:00+01:00  2022      2    1     0            1

Lage subset siden datamengden er så stor